# docker-compose up
# docker-compose run web rake db:migrate db:seed
#
version: '3.7'
services:
  db:
    image: postgres:13.1
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - DATABASE_HOST=db
      - POSTGRES_HOST_AUTH_METHOD=trust
  web:
    build: .
    command: bundle exec rails s -p 3707 -b '0.0.0.0'
    volumes:
      - .:/opt/rails_api
    ports:
      - "3707:3707"
    environment:
      - "RAILS_ENV=development"
      - "DATABASE_HOST=db"
      - "DATABASE_USER=postgres"
      - "DATABASE_NAME=north_by"
    depends_on:
      - db
volumes:
  db:
    driver: local
